[[ventana-custom-extensions]]
= VTx-family custom instructions: Custom ISA extensions for Ventana Micro Systems RISC-V cores
:revdate: 2022-08-07
:revnumber: 1.0.1
:revremark: Public release
:doctype: book
// :media: prepress
// Settings:
:idprefix:
:idseparator: -
:compress:
:experimental:
:reproducible:
:icons: font
:lang: en
:listing-caption: Listing
:sectnums:
:toc: left
:toclevels: 4
:data-uri:
:hide-uri-scheme:
:stem:
:footnote:
:xrefstyle: short
:WaveDromEditorApp: ~/wavedrom-cli/cli/wavedrom-cli.js
:source-highlighter: pygments
ifdef::backend-pdf[]
:source-highlighter: coderay
endif::[]


[preface]
== Front matter

Copyright (C) 2021-2022 by Ventana Micro Systems. +
All rights reserved.

=== Attributions

This document is based on the Asciidoctor documentation template designed at VRULL GmbH. +
Typeset with Asciidoctor.
Diagrams generated by Wavedrom.

The fonts used in this document are licensed under the Open Font License:

* M PLUS 1p,designed by the  M+ Outline Fonts Project;
* Fira Sans, designed for Mozilla FirefoxOS by Carrois in Berlin, Germany;
* Unna, designed by Omnibus-Type in Buenos Aires, Argentina;
* SourceCodePro, designed by Paul D. Hunt for use in user interfaces.

=== Contributors

Written by Greg Favor (Ventana Micro Systems) and Philipp Tomsich (VRULL GmbH). +
Production by VRULL GmbH.

=== Revision history

[cols="1,7"]
|===
|Version | Description

|1.0.0
|January 2022 +
Initial revision.

|1.0.1
|August 2022 +
Updated guidance for `conditional bitwise-and` sequences to expand to an `and` instruction followed by a `conditional bitwise-or` sequence, no longer depending on the Zbb extension (for the `andn` instruction).
|===

== Vendor-prefix for mnemonics

To avoid conflicts between mnemonics defined by different implementors of custom RISC-V extensions, each vendor-defined mnemonic is--in consequence--prefixed by a vendor-specific prefix: i.e., each vendor-defined mnemonic is structured as "_<vendor prefix>_ `.` _<mnemonic base name>_".

The vendor-prefix to all mnemonics defined by Ventana Micro Systems is "vt" (e.g., the "`maskc`" instruction becomes "`vt.maskc`").

== Custom extensions

This document describes the custom ISA extensions defined by Ventana Micro Systems.

// Include each of our custom extensions here
include::XVentanaCondOps/XVentanaCondOps.adoc[]

== Supported extensions (by core)

This chapter lists the custom extensions supported by each core/core-family.

[#vt1,reftext="VT1"]
=== VT1 core

The VT1 core implements the following custom extensions:

* <<#xventanacondops>>: conditional operations

== Instructions (in alphabetical order)

This chapter lists all custom instructions defined by Ventana Micro Systems in alphabetical order.

include::XVentanaCondOps/insns/vt.maskc.adoc[]
include::XVentanaCondOps/insns/vt.maskcn.adoc[]
